### ISSUE TITLE
allow multiple scripts in the `script_file` charm config

### ISSUE THREAD

**Issue by nishant-dash** [canonical/script-exporter-operator#18]
### Enhancement Proposal

the upstream exporter config seems to already support multiple scripts, so I believe it would be nice to have the `script_file` accepts multiple scripts too. Perhaps it could be called `scripts` and be a yaml list?
```yaml
script_name_1: |
  #!bin/bash
  echo hello
script_name_2: |
  #!/usr/bin/python3
  print("hello")
```

or something along those line
